- name: Set Hostname
  ansible.builtin.shell: set-hostname sonarqube

- name: Add SonarQube User
  ansible.builtin.user:
    name: sonarqube

- name: Download SonarQube
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-26.3.0.120487.zip
    dest: /home/sonarqube
    remote_src: yes
    owner: sonarqube
    group: sonarqube

- name: Create Java installation directory
  file:
    path: /opt/java
    state: directory
    mode: '0755'

- name: Download JDK
  get_url:
    url: "https://download.oracle.com/java/25/latest/jdk-25_linux-x64_bin.tar.gz"
    dest: "/tmp/jdk-25.tar.gz"
    mode: '0644'
    headers:
      Cookie: "oraclelicense=accept-securebackup-cookie"

- name: Extract JDK
  ansible.builtin.unarchive:
    src: /tmp/jdk-25.tar.gz
    dest: /opt/java
    remote_src: yes

- name: Install Java
  ansible.builtin.dnf:
    name: java-21-openjdk.x86_64
    state: installed

- name: Copy SonarQube service file
  ansible.builtin.template:
    src: sonarqube.service
    dest: /etc/systemd/system/sonarqube.service

- name: Start SonarQube Service
  ansible.builtin.systemd_service:
    name: sonarqube
    state: started
    enabled: yes