- name: Copy Elastic Repo file
  ansible.builtin.template:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Install elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: Start Elasticsearch
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Install kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed

- name: Start Kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: started
    enabled: yes


