- name: copy jenkins repo
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install jenkins
  ansible.builtin.dnf:
    name:
      - fontconfig
      - java-21-openjdk
      - jenkins
    state: installed

- name: Start Jenkins Service
  ansible.builtin.systemd_service:
    name: jenkins
    state: started
    enabled: yes

