{
 "title": "expense",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Used %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) (100 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) *100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_systemd_unit_state{exported_name=\"nginx.service\",state=\"active\"})",
     "legendFormat": "{{exported_name}}"
    },
    {
     "expr": "(node_systemd_unit_state{exported_name=\"backend.service\",state=\"active\"})",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "Server up Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"ec2\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Used %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Queue / drop",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(node_ethtool_pps_allowance_exceeded[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}